### ISSUE TITLE
Handle a use case when RDWs count themselves as being part of a record

### ISSUE THREAD

**Issue by yparesh** [AbsaOSS/cobrix#109]
We are able to parse a variable length file by setting "is_record_sequence" to "true". However the parsed data is "shifted" left by 4 bytes. We do have 4 byte RDW headers in the data. It seems Cobrix parser assumes that in addition to 4-byte RDW header there is 4 byte BDW header present in the data and hence consumes first 8 bytes from each row of the ebcdic data file effectively shifting actual data left by 4 bytes.

![image](https://user-images.githubusercontent.com/4328123/60055736-992e4b00-96ac-11e9-9954-bf0ca0b8a243.png)

**Comment by yruslan** [comment]
From the picture above I can see that the highlighted region for the RDW is 2 bytes, not 4 in your case.

![Screenshot 2019-06-25 at 09 02 53](https://user-images.githubusercontent.com/4082463/60076989-3202ac00-9729-11e9-9534-a10f38e6a5b9.png)

According to [the spec](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.idad400/d4357.htm):

> The record descriptor word is a 4 byte field describing the record. The first 2 bytes contain the length (LL) of the logical record (including the 4 byte RDW). The length can be from 4 to 32␠760. All bits of the third and fourth bytes must be 0, because other values are used for spanned records.

The values in your examples doesn't seem to match RDW since third and fourth bytes are not zeros.

Could you please elaborate more on your example? Where exactly record length information is stored in your case? Could you describe a full record and highlight which bytes are used for record length in your case.

**Comment by yparesh** [comment]
Thanks for your response. My bad. Please see below the corrected picture.

![image](https://user-images.githubusercontent.com/4328123/60081131-3914c480-96ff-11e9-86a6-20d189324645.png)

**Comment by yruslan** [comment]
This is much cleaner now, thanks. We haven't had data containing bot BDW and RDW yet, so that's maybe why it is parsing records like that. If 'is_record_sequence' or 'is_xcom' (they are just synonyms) is true Cobrix assumes each record starts with 4 byte RDW. Cobrix gets record length from RDW and throws these 4 bytes away since they are not expected to be a part of the copybook.

Currently Cobrix does not support BDWs since we never had a use case for that. I think what happens is that your copybook contains a 4 byte field describing RDW. But since Cobrix skips RDW before parsing a record the layout of the copybook shifts by 4 bytes. Try commenting out the RDW field in the copybook.

**Comment by yparesh** [comment]
Thanks for the clarification. Can you suggest a way to get the EBCDIC file from mainframe to Linux machine that preserves RDW headers? The team responsible for moving the file uses connect direct from Sterling software and thinks that either we can send BDW and RDW headers together or none. There is no option to send file with RDW headers alone.

**Comment by yruslan** [comment]
Sorry, we can't disclose anything about our internal systems. But we can help you to support record sequence files that have both BDWs and RDWs. There are several ways to achieve that.
- If you can provide us with a detailed description how BDWs and RDWs work and how the parser can use it to extract records and also provide an example file with a copybook, we can add a support for that in Cobrix. But this is a slower way since we are under heavy load from other projects.

or

- You can use custom record header parser functionality (see 'examples/spark-codec-app') to implement a parser for BDW+RDW headers yourself. When you can contribute that custom record header parser to Cobrix. We could 'implant' that parser as a core Cobrix functionality.

Overall, it does not seem too hard to support BDW+RDW files. Just need to understand precisely how it works. Let me know which way is better for you.

**Comment by yparesh** [comment]
I agree, it won't be too hard to support BDW+RDW files. 

Please see some links below. Unfortunately I won't be able to share internal copybooks/data. 

It is great idea for us to write custom record header parser functionality  to support BDW+RDW files and contribute that custom record header parser to Cobrix. We are a small team so let me run that by my manager.

Cobrix should take first four bytes of the record as RDW headers, correct? 
Also it should be reading the RDW headers for each record in the file, correct?
Any chance Cobrix might be taking byte numbers 5th to 8th from a record as RDW? I had a record with following 8 bytes at the beginning of a record (image below) and Cobrix threw error "RDW headers should never be zero (0,0,0,0).

 ![image](https://user-images.githubusercontent.com/4328123/60300680-1d730f00-98f5-11e9-9720-7cdf46a489ca.png)


https://www.ibm.com/support/knowledgecenter/zosbasics/com.ibm.zos.zconcepts/zconcepts_159.htm

https://www-01.ibm.com/support/docview.wss?uid=swg22011602

**Comment by yruslan** [comment]
Cobrix parses first 4 bytes as RDW. Could you please post the full error message? The error message should contain an offset where these 4 zerors were found.

I suspect that in your case the first RDW was read successfully, but the next record headers might be zeros. Also, looking at the headers I think your RDW might be big endian.
Try
```
.option("is_rdw_big_endian", "true")
```

**Comment by yparesh** [comment]
The full error message was, "RDW headers should never be zero (0,0,0,0). Found zero size record at 0. "

We already set     .option("is_rdw_big_endian", "true") ( big endian).

**Comment by yruslan** [comment]
This is very strange. Are you sure Cobrix points to the proper file (the one displayed in the screenshot)?

Sorry, it seems like a silly question, but for me something doesn't add up. What is your full Spark reader command (e.g. `spark.read...`)?

**Comment by yparesh** [comment]
I agree, even I had hesitations when posting that error message because it
has been days since we ran that copybook/datafile and got the error so I
might have jumbled up.

I am logged off from work at present, I will recheck/re-run, verify and let
you know this and other details soon.

Thanks
Paresh Yadav
416-688-1003

**Comment by yruslan** [comment]
Thanks! Let's double check everything again. From what I can see the file should be easily parsed with the current version of Cobrix.

**Comment by yparesh** [comment]
We verified that Cobrix points to the correct file/s. Here is what we found out to be the issue. NOt sure how to address it.

![image](https://user-images.githubusercontent.com/4328123/60469647-216b9d80-9c23-11e9-812b-9f4bff980d7f.png)

As you can see from the above image, the mainframe utility that sends us the EBCDIC data file is adding 4 bytes count to the RDW. Not sure why, may be it adds its own length (RDW length = 4 bytes) to the RDW value? Because of this 1st record gets parsed correctly. But all other records gets messed up.

We are trying to see if there is an option in the mainframe utility to avoid adding 4 bytes. Other than this, is there anyway we can account for this in Cobrix without writing custom header parser? 

I can think of a hack where we hardcode to subtract 4 bytes from the record_length in Cobrix code and compile our jar but that would not be clean.

**Comment by yruslan** [comment]
Thanks for the great explanation! This completely makes sense.
In our use cases RDW header din't count itself in record length. Your use case is different and RDWs count themselves as part of the record.

Let us add an option to control this behavior. No need to hardcode a hack :)

**Comment by yruslan** [comment]
The feature is merged.

Try `.option("is_rdw_part_of_record_length", true)` on the latest master (`0.5.2-SNAPSHOT`).
