### ISSUE TITLE
Can this copybook be parsed as multi segment use case?

### ISSUE THREAD

**Issue by yparesh** [AbsaOSS/cobrix#124]
Hi,

Below (image) is our copybook. The field in red rectangle is segment id. When we try to parse the ebcdic data file with .option("segment_field", "SRC1-DG-77.SRC1-DG-N") and .option("segment_filter", "111"), it works fine and gets data for SRC1-DG-77.SRC1-DG-N = 111 but when we try to parse the next segment with  .option("segment_field", "SRC1-DG-78.SRC1-DG-N") and .option("segment_filter", "222") we get an error "java.lang.IllegalStateException: Field 'SRC1-DG-78.SRC1-DG-N' is not found in the copybook." It seems like it is trying look for SRC1-DG-**78**.SRC1-DG-N in segment "77".

My question is - Can this copybook be considered as multi segment use case? Is so what will be the right way to parse this as multi segment.

![image](https://user-images.githubusercontent.com/4328123/60909182-365bb880-a243-11e9-83f8-9be30da5e651.png)

Thanks,
Paresh

**Comment by yruslan** [comment]
Hi Paresh,

- Try using full path to the segment id field e.g. `SRC1-PWR-78.SRC1-DG-78.SRC1-DG-N` for segment filtering. In your example you didn't include the first element of the path, it might confuse Cobrix. Alternatively, you can use "SRC1-DG-77.SRC1-DG-N" a s segment id field and filter by "222"
since location of this field is the same in both segments.
- For multisegment files it is expected for segments to redefine each other. I think 'SEC1-PWR-78' group should redefine 'SRC-PWR-77':
```
      01 SRC-PWR-78 REDEFINES SRC-PWR-77.
```
- Also, since all the segments have the same header, I'd recommend to extract that header in a separate GROUP andput it at the beginning of of the copybook.
