### ISSUE TITLE
Issue with float

### ISSUE THREAD

**Issue by mevivs** [AbsaOSS/cobrix#128]
I am getting issue while converting a float value(COMP-2) "+3.229367  E+02". It gives me 1.4202907015092298E15 as output

**Comment by mevivs** [comment]
@yruslan Sure. I can certainly provide this. Please share email id or please drop me a test mail at vivek.mishra@yahoo.com

**Comment by mevivs** [comment]
x-special/nautilus-clipboard
copy
file:///home/vivek/Downloads/tpumpfile_d0709

**Comment by mevivs** [comment]
[issue-sample.zip](https://github.com/AbsaOSS/cobrix/files/3382201/issue-sample.zip)

**Comment by mevivs** [comment]
@yruslan attached sample copybook and data file

**Comment by yruslan** [comment]
Thanks, will take a look. Just a couple of more things.
- Do you have parsed floating point values from the first several records? Since I don't know what actual values should be it is hard to see when it is parsed correctly or not. The values provided in the description is a good start. 
- Maybe you have a pointer to a specific IBM floating point format used? According to [this link](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzase/sc092540204.htm) IBM started to use IEEE-754 for floating point formats at some point. But they have a vendor specific format as well.

I'm going to start looking if your data fits IEEE-754 in big endian or little endian order. If that is the case it is easily solvable.

**Comment by mevivs** [comment]
![newoutput](https://user-images.githubusercontent.com/456249/61061850-0b9c6c00-a3cb-11e9-825b-bb808a4b5969.jpg)

**Comment by mevivs** [comment]
@yruslan Thanks! attached output screen shot.

**Comment by yruslan** [comment]
Perfect

**Comment by mevivs** [comment]
@yruslan is there a way to over ride dataframe schema? i tried 
session.read().format("cobol").schema(schema).  

but no luck

**Comment by yruslan** [comment]
Schema overriding is not supported. Each input type in a copybook corresponds to an exactly one Spark type. If you want to change output Spark type you need to use casting.

But I'm wondering what are you trying to achieve by overriding a schema?

**Comment by mevivs** [comment]
Was trying to enforce certain schema(not much of use). Btw to share, tried changing byte order at binaryutils.decodedouble and convert using bytebuffer. but no luck. Byte[] itself is not received correct

**Comment by yruslan** [comment]
In the copybook you've attached the `A11` field has `COMP-1` format, although the layout suggests the type is actually `COMP-2`. After changing the type of `A11` to `COMP-2` the data seems to be aligned to the copybook.

I've tried but big and little-endian IEEE0754 and also IBM floating point format according to [this page (see double-precision section)](https://en.wikipedia.org/wiki/IBM_hexadecimal_floating_point). Unfortunately, no combination of 'endness' and floating point format produced the expected value of `3.229367E+02`.

Encoded value is `43 14 2E FC CA F7 09 B7`. According to IBM floating point format the first bit is the sign (0 = positive). Therefore the encoded data is definitely in big-endian order (since B7 has the msb of 1 and the number decoded will be negative for all little-endian encodings).
The exponent is `43 => 100 0011 - 64 = 3`. The significand is `14 2E FC CA F7 09 B7 => 5681162806036919`. So according to the IBM format formula the value is
```
16^3 * 0.5681162806036919 = 4096 * 0.5681162806036919 = 2327.004285352722
```

This means that the floating format used is not the one of the ones I've tried.

Now the only thing we can do is try to find the correct floating point format matching your use case. If you could point out to the exact floating-point format used in your data it would speed up resolution of this issue.

**Comment by mevivs** [comment]
@yruslan looks like its converting to decimal floating point. Hexdecimal value for  1.4202907015092298E15 is 43142EFCCAF709B7.    Attaching screenshot for reference

**Comment by mevivs** [comment]
![image007](https://user-images.githubusercontent.com/456249/61145818-6b1b7a00-a4a6-11e9-82c4-8038eae553cf.jpg)

**Comment by mevivs** [comment]
![image002](https://user-images.githubusercontent.com/456249/61145823-6eaf0100-a4a6-11e9-8e2a-d96581528809.jpg)

**Comment by yruslan** [comment]
Yes, this is exactly what's happening. Do you know what actual representation is used in your case so the same bytes encode "3.229367E+02"?

**Comment by mevivs** [comment]
@yruslan tried https://github.com/enthought/ibm2ieee. It gives the correct value. Not sure but please take a look if it helps!

**Comment by mevivs** [comment]
![Screenshot from 2019-07-01 15-19-42](https://user-images.githubusercontent.com/456249/61355981-673f7d00-a843-11e9-9d99-8ab7a5c39abc.png)

**Comment by mevivs** [comment]
@yruslan  Not sure, if got chance to look at github project(mentioned above).  Primarily looks like 
https://github.com/enthought/ibm2ieee/blob/master/ibm2ieee/_ibm2ieee.c  does the trick for correct conversion.

**Comment by yruslan** [comment]
Great! Thanks for the links, will take a look.

**Comment by yruslan** [comment]
Thanks for the links, it is really helpful. The code is quite involved, will take me a couple of days to integrate it into Cobrix. Need to support both single and double precision (COMP-1 and COMP-2).

**Comment by mevivs** [comment]
Sure. Thanks

**Comment by yruslan** [comment]
Support for IBM floating point numbers is added in `0.5.4-SNAPSHOT`. You can try to test this from Sonatype snapshots repository. `0.5.4` will be released today.

If you have example encoded data for `COPM-1` as well, it could be very useful since I'm not quite sure if encoding is done correctly for `COMP-1` single precision numbers.

**Comment by mevivs** [comment]
@yruslan  Verified for COMP-2, works fine. Thanks
