### ISSUE TITLE
Writing complex copybook structure from Spark as  EBCDIC  output format

### ISSUE THREAD

**Issue by diwakar2050** [AbsaOSS/cobrix#178]
I have use case to read a complex copybook  EBCDIC data file which has REDEFINES, OCCURS with  COMP-3 , COMP  types using Spark, I know this tool has features to achieve it. Once I read EBCDIC file in Spark , i need to write the data after processing as output EBCDIC format. Will this tool will be able to do it?

**Comment by yruslan** [comment]
Hi @diwakar2050. Thanks for your interest in the project!

Currently, `spark-cobol` can be used only for reads. So you can read EBCDIC files and write your processing output to any format supported by Spark.

However, `spark-cobol` does not support writing to an EBCDIC file. We do not have plans to implement a writer yet. But it may change in the future.

**Comment by snrsamy** [comment]
Thanks for this amazing tool, super fast in bringing in EBCDIC data  for Spark processing. In last 2-3 years, have you considered adding WRITE capability to an EBCDIC file ?

**Comment by yruslan** [comment]
Thanks, @snrsamy for the interest in the project! Currently, the ebcdic file writer is still in plans. And I'm not sure when we are going to start implementing it.

In order to implement the writer we need a use case, otherwise, we can implement something that is not going to be very usable. Here is a discussion on the topic: https://github.com/AbsaOSS/cobrix/issues/415

**Comment by snrsamy** [comment]
Thanks a bunch on the update
