### ISSUE TITLE
Support for reading from S3

### ISSUE THREAD

**Issue by chandrasekaravr** [AbsaOSS/cobrix#188]
@yruslan 
As of now, it is easy to specify local file system paths or hdfs paths for the copybooks  or the input EBCDIC files. As i am running it from EMR, i tried setting up the S3 filesystem in my spark context and tried to load these files from S3 and it failed with Wrong FS exception.

Is there any specific difficulty dealing with S3?

**Comment by yruslan** [comment]
We are aware of this issue (#146), S3 is not supported yet, but it is in our plans to add support.

The reason it is not supported yet is not that there is a particular difficulty with S3. The reason is that in order to make Cobrix perform well on variable-record length files, we added several HDFS-specific optimizations (e.g. data locality awareness). In order to add support for S3 we need to port these optimizations to that FS.

**Comment by chirags83** [comment]
Do we have this solution available..?
To read directly from S3 instead of HDFS..?

**Comment by yruslan** [comment]
We don't have a solution yet, but we will start investigating it soon.
I expect a solution to this to be available in a couple of months.

**Comment by yruslan** [comment]
S3 storage should be supported in `spark-cobol` version `2.2.0`.

Please, let me know if it works for you.

**Comment by XaviForde001** [comment]
Hello, I tested the S3 storage with s3a connecter today and it was successful. Many thanks for adding this functionality!

**Comment by XaviForde001** [comment]
Hi, 
In the S3 example Hadoop 2.7.3 which I have packaged as an Uber jar and run on AWS Glue/EMR successfully (using pyspark). However for local development we use temporary AWS credentials using aws_session_token which requires Hadoop 2.8+. I have tried to build the S3 example with Hadoop 2.8.5 which is reccommended by AWS [https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-1.0/spark-2.4.3-bin-hadoop2.8.tgz](https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-1.0/spark-2.4.3-bin-hadoop2.8.tgz) but haven't been successful so far.

Does Cobrix specifically rely on Hadoop 2.7.3 or should it be possible to rebuild with Hadoop 2.8.5? 
Any help much appreciated!

**Comment by yruslan** [comment]
Cobrix should not depend on the version of Hadoop. That said, we haven't tested it on a cluster having Hadoop > 2.7.x yet.

What kind of issues are you experiencing?

**Comment by XaviForde001** [comment]
Here is summary of what I have tried, apologies for the long tracebacks..

Using the Uber Jar `spark-cobol-s3-0.0.1-SNAPSHOT.jar` as per current pom.xml i received the following error when trying to read from S3 locally with session credentials:

An error occurred while calling o597.load.\n: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain\n\tat com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)\n\tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3521)\n\tat com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1031)\n\tat com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:994)\n\tat org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:297)\n\tat org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)\n\tat org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)\n\tat org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)\n\tat org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)\n\tat org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)\n\tat org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)\n\tat za.co.absa.cobrix.spark.cobol.utils.FileUtils$.getFiles(FileUtils.scala:55)\n\tat za.co.absa.cobrix.spark.cobol.source.CobolRelation.getListFilesWithOrder(CobolRelation.scala:110)\n\tat za.co.absa.cobrix.spark.cobol.source.CobolRelation.<init>(CobolRelation.scala:77)\n\tat za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:58)\n\tat za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:47)\n\tat org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)\n\tat org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)\n\tat org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)\n\tat org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\n"

The spark session is using hadoop 2.7.3 from the `spark-cobol-s3-0.0.1-SNAPSHOT.jar` which I believe does not support the org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider class needed to authenticate using aws_session_token. [SO thread about this.](https://stackoverflow.com/questions/51774163/pyspark-not-using-temporaryawscredentialsprovider)

Updating the pom.xml in to use spark 2.4.3 and hadoop & hadoop-aws 2.8.5 as per below. jackson-databind dependency changed from `2.6.7.3` to `2.6.7.1` to match spark 2.4.3 rather than spark 2.4.7. Using this gave the jackson error when building the spark session, also shown below.

```<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>spark-cobol-s3</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <packaging>jar</packaging>

    <properties>
        <encoding>UTF-8</encoding>
        <scala.version>2.11.12</scala.version>
        <scala.compat.version>2.11</scala.compat.version>
        <scalatest.version>3.0.0</scalatest.version>
        <spark.version>2.4.3</spark.version>
        <spark.cobol.version>2.2.0</spark.cobol.version>
    </properties>

    <dependencies>
        <!-- Scala -->
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scalap</artifactId>
            <version>${scala.version}</version>
            <scope>provided</scope>
        </dependency>


        <!-- Libraries -->
        <dependency>
            <groupId>za.co.absa.cobrix</groupId>
            <artifactId>spark-cobol_${scala.compat.version}</artifactId>
            <version>${spark.cobol.version}</version>
        </dependency>

        <!-- S3 Support -->
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-aws</artifactId>
            <version>2.8.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>2.8.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.6.7.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.6.7</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
	    <artifactId>jackson-module-scala_${scala.compat.version}</artifactId>
            <version>2.6.7.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.2</version>
        </dependency>

        <!-- Spark -->
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.compat.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.compat.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala.compat.version}</artifactId>
            <version>${scalatest.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/scala</sourceDirectory>
        <testSourceDirectory>src/test/scala</testSourceDirectory>

        <plugins>
            <!-- compile Scala sources -->
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <scalaVersion>${scala.version}</scalaVersion>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>


            <!-- enable scalatest -->
            <plugin>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <!-- <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory> -->
                    <junitxml>.</junitxml>
                    <filereports>WDF TestSuite.txt</filereports>
                    <!--<skipTests>true</skipTests>-->
                    <!-- increase heap size for scalatest -->
                    <argLine>-Xmx1024m</argLine>
                </configuration>
                <executions>
                    <execution>
                        <id>test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Generate an uber jar for spark-submit -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <transformers>
                        <!-- This allows to support several library data sources for Spark by referring to them by short name. -->
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    </transformers>
                </configuration>
            </plugin>

        </plugins>

    </build>
```

Error:

21/01/08 16:35:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/01/08 16:35:31 ERROR MetricsSystem: Sink class org.apache.spark.metrics.sink.MetricsServlet cannot be instantiated
21/01/08 16:35:31 ERROR SparkContext: Error initializing SparkContext.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:200)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:194)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:194)
	at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:102)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:514)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:537)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:448)
	at org.apache.spark.metrics.sink.MetricsServlet.<init>(MetricsServlet.scala:48)
	... 26 more

**Comment by yruslan** [comment]
It seems like a compatibility issue between Spark and Hadoop libraries.
Looks like the error happens at the stage of Spark Session creation before any spark-cobol code is loaded.

I spent some time solving binary compatibility issues to make `spark-cobol-s3` example work in local mode. `jackson-*` libraries are especially different between different versions of Spark and Hadopp. I can try to look and make the project to link with Hadoop 2.8, but no guarantees. Might be better luck trying Spark 3.0.1 and Hadoop 3.2 (the combination which is officially supported by Spark).

But can I ask you what are you trying to achieve? I see the project run from PySpark. Are you using EMR or running on a EC2 instance or from a non-AWS computer?

**Comment by XaviForde001** [comment]
Our data platform runs on AWS Glue, which is a severless glue platform offered by AWS and I believe backed by EMR behind the scenes. The jobs run in AWS Glue reading directly from S3 with the new `spark-cobol-s3-0.0.1-SNAPSHOT.jar` jar and this has worked so far out of the box without any issues.
I am trying to replicate this locally for development and testing but as we use session tokens to authenticate in local mode it will not work with Hadoop 2.7.3. I also need other devs to be able to run these tests so I will need to get it to work with the AWS recommended spark-hadoop distribution we are all using (spark 2.4.3 and hadoop 2.8.5).

I concluded also the jackson dependencies between spark and hadoop are causing the issue. I think it might be easiest from me to try to resolve the jackson dependency in scala project with hadoop2.8.5 and spark 2.4.3 first before running in pyspark. I will let you know if I succeed... if you did get the time to build hadoop 2.8.x example that would also be great.

**Comment by yruslan** [comment]
Hmm... I haven't tried Glue, but my thinking is that you don't need `spark-cobol-s3-0.0.1-SNAPSHOT.jar` to run a pipeline from Glue. EMR should have both Spark and Hadoop libraries provided and they might be perfectly tuned to be binary compatible (since they are provided by AWS). `spark-cobol-s3-0.0.1-SNAPSHOT.jar` is just an example how these jobs can be ran in local mode.

If your job uses PySpark, I'd recommend taking spark-cobol jar and its dependencies:
- spark-cobol_2.11-2.2.0.jar
- cobol-parser_2.11-2.2.0.jar
- scodec-core_2.11-1.10.3.jar
- scodec-bits_2.11-1.1.4.jar
- antlr4-runtime-4.7.2.jar

You can download all of them from Maven. E.g. https://search.maven.org/search?q=cobrix

Alternatively, you can use a smaller uber jar that does not include Hadoop and S3-related libraries: https://github.com/AbsaOSS/cobrix/tree/master/examples/spark-cobol-app 
This project has all the above jars included in its uber jar.

You should be able to use 'cobol' data source from PySpark:
```python
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

df = spark.read.format('cobol').options(copybook='s3a:///path/to/copybook.cob').load('/path/to/data')
```

This doesn't solve running in local mode, however. Sorry, I' don't have much experience with PySpark either, but I'd start with providing the above jars instead of  `spark-cobol-s3-0.0.1-SNAPSHOT.jar` to PySpark to get cobol support. And, if PySpark does not contain Hadoop libraries, I'd provide them separately, the version that is required. 

Do you use S3 for non-mainframe files for local jobs, right? Adding support for cobol source should be as simple as adding the above jars to the classpath.

I hope it makes sense to you. Please, let me know if you have progress setting up local execution with Hadoop 2.8. I might take a look if I can change the `spark-cobol-s3` example project to use Hadoop 2.8.5.

**Comment by yruslan** [comment]
An example has been added for running Spark locally with Hadoop 3.2 that supports advanced AWS authentication mechanisms and can be ran locally of from EC2:

https://github.com/AbsaOSS/cobrix/tree/master/examples/spark-cobol-s3-standalone
