### ISSUE TITLE
Issue loading multiple records VB file

### ISSUE THREAD

**Issue by ss23697** [AbsaOSS/cobrix#218]
Hi,

We are facing an issue when reading a multiple records variable length file. The dataframe is only getting loaded with first record. Please find below details:

Copybook:

       01 DEPARTMENTS.
           05 DEPT                     PIC X(07).
           05 SUITE                    PIC X(03).
           05 EXTENSION                PIC X(04).
           05 EMPLOYEES                PIC 9(01).
           05 PERSON                   OCCURS 0 TO 10 TIMES 
                                       DEPENDING ON EMPLOYEES.
            10 NAME                     PIC X(10).
            10 WAGE                     PIC 9(01).9(02).
           05 DEPT-ID                  PIC 9(06).

Sample file:

3500Sales  01A23521S. Sen    2.99889900
4900Support01B12252J. Halpert5.90A.Martin  5.95112233

The dataframes are loading as below:

scala> df4.show(false)
+-----------------------------------------------+
|DEPARTMENTS                                    |
+-----------------------------------------------+
|[Sales, 01A, 2352, 1, [[S. Sen, 2.99]], 889900]|
+-----------------------------------------------+
  where as when we interchange the positions of records, we are seeing df like below:

scala> df3.show(false)
+-----------------------------------------------------------------------+       
|DEPARTMENTS                                                            |
+-----------------------------------------------------------------------+
|[Support, 01B, 1225, 2, [[J. Halpert, 5.90], [A.Martin, 5.95]], 112233]|
+-----------------------------------------------------------------------+

Can you help what are we doing wrong and how to read all the records from the file.

Thanks and regards
Subhankar

**Comment by yruslan** [comment]
Hi, please attach the example copybook, the data file and provide the exact statement that you use for loading the data (e.g. `spark.read...`).

**Comment by ss23697** [comment]
[12326a4c756fe42a5ae0b3e4482da8df.zip](https://github.com/AbsaOSS/cobrix/files/3878609/12326a4c756fe42a5ae0b3e4482da8df.zip)


Hi ,

Please find attached copybook and vb file. The statement used is as below:

scala> val df = spark.read.format("cobol").option("copybook","file://<loc>").option("is_record_sequence","true").option("variable_size_occurs","true").load("<loc>")

Thanks
Subhankar

**Comment by yruslan** [comment]
To read a variable record length file in Cobrix you need to have either a fields that contains record length for each record, or (preferred) RWD headers for each record. 

The input file that you have provided does not contain valid RDWs. RDW is a binary 4 byte field. Your records also start with a 4 byte fields, but they are definitely not binary:
![Screenshot 2019-11-22 at 10 25 38](https://user-images.githubusercontent.com/4082463/69414310-bd04c400-0d12-11ea-8ef8-120b55f81e23.png)
I think in this case the first record was successfully parsed purely by chance. Cobrix inpertreted the first field as an RDW header that has a very large value. Since the value is larger than the file size, the record was truncated to the file size. So the whole file was parsed as a single record.

More on RDWs here: https://www.ibm.com/support/knowledgecenter/en/SSB27U_7.1.0/com.ibm.zvm.v710.dmsa5/dup0009.htm

Alternatively, if you want to parse this file using the fields that you have (provided 3500 and 4900 are related to record size), you can use a custom record header parser. More on in in README and the project has an example usage of a custom record header parser in `/examples`.

**Comment by ss23697** [comment]
Hi,

Could you please provide the code snippet for the example scenario given in the case. 
We tried to create the custom class but we are getting error as below:

IllegalStateException: Custom RDW headers should never be zero (-13,-11,-16,-16) at file offset 4.

We defined record length in the getRecordMetadata() method as

val recordLength = header(1).toInt + 10*(header(0).toInt)
RecordMetadata(recordLength, isValid=true)


Thanks
Subhankar

**Comment by yruslan** [comment]
The idea behind an RDW is that every record begins with a fixed-length header that specifies the size of the record. Usually, RDWs are 4 byte headers where two bytes are zero and two other bytes specify record size. Your case is different, however, since the numeric field at the beginning of each record is not binary.

In order to use a custom record header parser, we need to understand how header fields correspond to record sizes. Specifically, what is the meaning of '3500' and '4900' in your case?

**Comment by ss23697** [comment]
Among the first four positions of each record in the file,  first two positions denote the record length in integer format, meaning, first two positions i.e 35 denotes 35 is the length of 1st record. The rest two positions have no significance and is hence 0 and 0.

Similarly for second record, 49 is the length of entire second record.

These lengths are excluding first 4 header positions.

**Comment by yruslan** [comment]
Cool, will try to come up with a code snippet for you.
Will try to use a record length field first. If that doesn't work, will use a custom record header parser.

**Comment by yruslan** [comment]
It seems that a custom record header parser is unnecessary. You can just add the record length field to the copybook. The difference between the value in the record length field and the actual record size is actually 5 (determined by looking at the size of actual records).

Here is a new copybook (notice `REC-LEN` and the FILLER):
```
       01 DEPARTMENTS.
           05 REC-LEN                  PIC 9(02).
           05 FILLER                   PIC X(02).
           05 DEPT                     PIC X(07).
           05 SUITE                    PIC X(03).
           05 EXTENSION                PIC X(04).
           05 EMPLOYEES                PIC 9(01).
           05 PERSON                   OCCURS 0 TO 10 TIMES 
                                       DEPENDING ON EMPLOYEES.
            10 NAME                     PIC X(10).
            10 WAGE                     PIC 9(01).9(02).
           05 DEPT-ID                  PIC 9(06).
```

Here is a code snippet to load the file:
```scala
    val df = spark
      .read
      .format("cobol")
      .option("copybook", "vb_copy2.txt")
      .option("schema_retention_policy", "collapse_root") 
      .option("record_length_field", "REC-LEN")
      .option("rdw_adjustment", 5)
      .load("vb_file23.txt")
```

Here is the output:
```
+-------+-------+-----+---------+---------+--------------------------------------+-------+
|REC_LEN|DEPT   |SUITE|EXTENSION|EMPLOYEES|PERSON                                |DEPT_ID|
+-------+-------+-----+---------+---------+--------------------------------------+-------+
|35     |Sales  |01A  |2352     |1        |[[S. Sen, 2.99]]                      |null   |
|49     |Support|01B  |1225     |2        |[[J. Halpert, 5.90], [A.Martin, 5.95]]|null   |
+-------+-------+-----+---------+---------+--------------------------------------+-------+
```

**Comment by ss23697** [comment]
Hi,

Thankyou for helping us use the right option.  We are able to parse multiple records from the file now.

We are closing the issue.

Thanks
Subhankar
