### ISSUE TITLE
Error while parsing copybook definition: PIC 9(15)+.

### ISSUE THREAD

**Issue by pelatimtt** [AbsaOSS/cobrix#23]
I hit a copybook with the following definition: PIC 9(15)+. 
The copybook parser is not able to handle it. What isthe meaning of the + in this case ?

**Comment by yruslan** [comment]
Thanks for the interest. The '+' symbol looks like an explicit sign position. We currently don't support it since we don't have an example copybook and mainframe file that contains it.
It is likely an equivalent to `PIC 9(15) SIGN TRAILING SEPARATE.` but I'm not 100% sure. If you can confirm that that is the case we can add support for such PICs in the future versions.
If '+' means something else, we need an example copybook + data file to add support for this.

**Comment by pelatimtt** [comment]
I will find out the exact meaning and let you know. Thanks

**Comment by pelatimtt** [comment]
9(15)+ basically means that, in addition to the 15 numeric characters the last character is the sign, which can be + or -.
For example 9(3)+ is a valid picture for a value 345-

**Comment by yruslan** [comment]
Great, Thanks for the confirmation. So `9(15)+` is the same as `PIC S9(15) SIGN TRAILING SEPARATE` and it can be used as a workaround for now. In the meantime we are going to add the support for the '+' sign in the next release.

**Comment by yruslan** [comment]
I'd like to let you know this feature is selected for implementation. Expect it to be available in the next release.

**Comment by touseefzaki** [comment]
I have a similar problem when parsing my cobol file 
**10  WS-FMT6-PACK                 PIC  Z(5).**
When the reader comes at this like it throws error saying incorrect data

**Comment by yruslan** [comment]
Thanks, we will add the support for 'Z' as well. From Spark perspective it is similar to '9(5)'.

**Comment by touseefzaki** [comment]
Problem with Z is fixed and it works fine now. I implemented in my Use case, Thanks @yruslan

**Comment by yruslan** [comment]
This task should be resolved in 0.3.1. If no more issues encountered it will be closed in a week.
