### ISSUE TITLE
COMP-3 fields after Variable occurs clause is not getting allocated

### ISSUE THREAD

**Issue by eapframework** [AbsaOSS/cobrix#259]
I am trying to read Mainframe data using following copybook structure. It has variable occurs clause and Comp-3 fields after variable occurs. Attached full copybook and pasted portion of copybook below. 

[copybook-full.txt](https://github.com/AbsaOSS/cobrix/files/4258773/copybook-full.txt)

       02  RDT-ADDL-DATA-GROUP.                                     
             05  RDT-ADDL-DATA  OCCURS 0 TO 99 TIMES
                              DEPENDING ON RDT-ADDL-SEGS-NO.            
                10  RDT-ADDL-SEG-KEY.                                
                         15 RDT-ADDL-SEG-KEY-PROD  PIC X(02).             
                         15 RDT-ADDL-SEG-KEY-TYPE  PIC X(01).             
                10  FILLER                    PIC X(47).             
       02  RDT-LAST-TX.                                             
               03  RDT-CENTURY-JULIAN-POST-DATE  PIC S9(7) COMP-3.      
               03  RDT-LS-IVA-AM                 PIC S9(11)V99 COMP-3.  
               03  RDT-DATA.                                            
                      05  RDT-TLF-MTHD-NM           PIC X(08).             
                      05  RDT-ADJ-ORGN-TRAN-DT      PIC X(06).             
                      05  FILLER                    PIC X(03).             
         02  RDT-ADDL-FIELDS.
                 03  RDT-1098-PREV-INTR-THRD-AM    PIC S9(15)V99 COMP-3.
                 03  RDT-1098-PREV-INTR-TOTL-AM    PIC S9(15)V99 COMP-3.
                 03  RDT-MRCH-ISO3-CTRY-CD         PIC X(3).
                 03  RDT-MAE-CNCY-CD               PIC X(3).
                 03  RDT-ASSC-CNCY-CNVR-CD         PIC X.
                 03  RDT-CRSS-BRDR-CNCY-IN         PIC X.
                 03  RDT-CRSS-BRDR-CHRG-IN         PIC X.
                 03  RDT-CNCY-CNVR-CD              PIC X.
                 03  RDT-CNCY-CNVN-IN              PIC X.
                 03  RDT-SAM-SKIP-QUE-CD           PIC X.
                 03  RDT-INTR-TYPE                 PIC X.
                 03  RDT-DCLN-AVLB-CRDT-AM         PIC S9(15)V99 COMP-3.
                 03  RDT-MRCH-MC-SC-CODE           PIC X(2).
                 03  RDT-CNCY-CNVR-FEE-AM          PIC S9(11)V99 COMP-3.
                 03  RDT-CRSS-BRDR-FEE-AM          PIC S9(11)V99 COMP-3.
                 03  RDT-PYMT-TYPE-CD              PIC X(02).
                 03  RDT-PFM-RSN-CD                PIC X(3).
                 03  RDT-FEE-ATTR-GLOBAL-CD        PIC X(3).
                 03  FILLER                        PIC X(16).

Code below:

        val df = spark.read.format("cobol").option("copybook","Mdet5.txt").option("debug_ignore_file_size", "true").option("file_start_offset", "4").option("record_length_field", "RECORD-LEN").option("schema_retention_policy", "collapse_root").load("mcy_mdet.dat")

I tried option("variable_size_occurs", "true"), but values are getting shifted to the left. I think some bytes were allocated to Header in the beginning. But I don't RDW header to be allocated since i have RECORD-LEN field in my copybook.

When i process with above code, COMP-3 fields after Variable occurs clause are not getting allocated. I am not seeing these fields (RDT-CENTURY-JULIAN-POST-DATE, RDT-LS-IVA-AM, RDT-1098-PREV-INTR-THRD-AM, RDT-1098-PREV-INTR-TOTL-AM, RDT-DCLN-AVLB-CRDT-AM, RDT-CNCY-CNVR-FEE-AM, RDT-CRSS-BRDR-FEE-AM)  in the output df.  Please help! 

Input file opened in Hex editor below:
 
![Input file opened in Hex editor](https://user-images.githubusercontent.com/61295496/75399229-54088b80-58c1-11ea-8134-ebd1034c4b18.jpg)

**Comment by yruslan** [comment]
What about fields with `PIC X.`, `PIC X(3)` and `PIC X(16)`? Are they correct?

**Comment by eapframework** [comment]
Yes. The PIC X, PIC X(3), and PIC X(16) fields are getting allocated in the output df. Only Comp-3 fields are missing.

**Comment by yruslan** [comment]
It is strange. COMP-3 values have such an encoding that not every character sequence corresponds to a value. So incorrect bytes cause COMP-3 fields to become `null`.
The fields that have PIC of `X`, `X(3)`, etc are always non-null. So the presence of values in these fields doesn't mean they are correct.

I think in your case there is a shift of data due to mismatch offset or a not complete correspondence between the copybook and the data file. This leads to the situation when COMP-3 fields are not decoded correctly. This needs to be carefully investigated to determine when this shift happens and how many bytes it spans.

**Comment by eapframework** [comment]
COMP-3 fields are not present in the output df itself. Only PIC values are displayed.  Comp-3 fields are missing. I will paste the output screenshot in few mins.

**Comment by yruslan** [comment]
The COMP-3 fields are missing because the sequence of bytes cannot be decoded into a number. I wish I could help, but it requires knowledge of the copybook and the data. You need to identify when data starts to shift against the copybook and why.
There is an option `.option("rdw_adjustment", 0)`. Although it says RDW, it adjusts length returned by `RECORD-LEN` as well. If the usage of `RECORD-LEN` shifts the data, you can try to adjust the length to the actual length by trying various values of the adjustments.

Another suggestion. Could you attach a JSON file of the first parsed record, I'll take a look, maybe I can find something obvious. But no guarantees.

**Comment by eapframework** [comment]
I have fixed the problem.  I removed the first 4 bytes in the file manually and removed option(file_start_offset, 4) and added option(variable_size_occurs, true) in the code.  I think file_start_offset and variable_size_occurs option does not work well together. But have to do more testing.  Thanks a lot for your help!
