### ISSUE TITLE
Reading the mainframe files data as text field irrespective of the copybook data type

### ISSUE THREAD

**Issue by chanduhawk** [AbsaOSS/cobrix#291]
## Background
If the data does not match with the data type of copybook while reading with cobrix the invalid data becomes null.

## Feature
Can we read all the data by text fields irrespective of the copybook data type so that no data would be lost while reading. It’s just like reading a csv file with all the data type as string

## Example [Optional]
A simple example if applicable.

## Proposed Solution [Optional]
Solution Ideas 
1. 
2. 
3.

**Comment by yruslan** [comment]
This is a tricky question. The simple answer is no, we currently do not support this. And I'm not sure what is the way to support it that might be helpful.

COBOL has a system of types and formats and some of these types have values that do not have meaning (semantic mapping).

Let's consider 2 approaches.
1. **Decoding data type format**. For instance, binary-coded decimal (BCD) can convert HEX values of `54 33 21` to the number `543321`. So if the copybook defines the field as being a BCD encoded number Cobrix converts it to numbers. But if a value `54 A3 21` is encountered, it is invalid from BCD perspective since 'A' is not a decimal number. So there is no mapping from that value to a number.

2. **Leaving raw values**. If a field is defined as BCD number but we always put raw values to the filed, a BCD number '54 33 21' will be converted to a string having 3 characters 0x54, 0x33, 0x21. And while for any character sequence a string is possible, the field losses its meaning as a number.

3. **Leaving raw numbers only for incorrect values**. We can write numbers as numbers when decoding is possible and write raw values otherwise. But in this case, we lose the ability to identify which value is correct.

4. **Additional debugging fields**. We have `.option("debug", "true")` which generates fields having additional values having the original data in HEX encoding. We can add an option to create these fields not as HEX encoding, but as actual raw values. This might be a viable solution.

Please, try the `debug` option. Let us know if it is sufficient for your use case or you would prefer having raw values as debugging fields.

**Comment by chanduhawk** [comment]
Thanks for the quick reply. I checked the #4 option to make debug=true. Though it created the HEX number but while converting the HEX values to the character its not generating the actual value. 

For value 01/11/2012 it generated the HEX as F0F161F1F161F2F0F1F2

so when i tried to convert this HEX to ASCII it didnt generate back the original value 01/11/2012. Please suggest

**Comment by chanduhawk** [comment]
For packed Decimal Comp3 S9(2)V999 for the value 12.000 we are getting the HEX as 00000000012000C. but while converting to string with characterset Cp037, its not working as intended

**Comment by yruslan** [comment]
The raw values are presented exactly the same way as they were in the original file, no encoding conversion is happening.

I'm trying to understand what do you want to achieve. Could you please provide a made-up example? Something like: "for fields having raw values so and so we want values to be so and so".

**Comment by chanduhawk** [comment]
For example my copybook file is as below

**01 StudentDetail
	10 Name PIC A(10)
	10 ID PIC S9(4) COMP
	10 Mark PIC S9(10)V999 COMP-3**

after enabling the debug option while loading the ebcidic file I am getting the dataframe as below

**Name	Name_debug	ID	ID_debug	        Mark	Mark_debug**
John	D1D6C8D5	1	0001		15.000	0000000015000C

So if you will see the Mark_debug column if I want to reverse engineer the 0000000015000C to 15.00 then how should I know whether the actual ASCII value in MARK as 15.000 or 015.000. Or is it the case that in ebcidic binary format the data wont come like 015.000. i.e can the data come like this in Mark column which is also a valid data and alligned to datatype.

**Name	Name_debug	ID	ID_debug	        Mark	Mark_debug**
John	D1D6C8D5	1	0001		**015.000**	0000000015000C

**Comment by yruslan** [comment]
> So if you will see the Mark_debug column if I want to reverse engineer the 0000000015000C to 15.00 then how should I know whether the actual ASCII value in MARK as 15.000 or 015.000. 

The difference between `15.000` and `015.000` is the matter of interpretation of binary data that comes in. The copybook does not describe whether there should be a leading zero when the value is displayed or not. And since it is not described in the copybook, Cobrix cannot do much about it.

Another way to look at it is that `15.000` and `015.000` are the same values since they semantically map to the same mathematical number `15`.

**Comment by chanduhawk** [comment]
Thats correct, but our requirement is to read the raw value as it is. so in this scenario if i will read the mark field as text field then 15.000 and 015.000 as two different thing. So basically we need to read the value as it is without manipulating anything.

**Comment by yruslan** [comment]
Okay. I have a question to you too. What in the copybook says that `15.000` is modified while `015.000` is the original value?

**Comment by chanduhawk** [comment]
no it is not mentioned, but I am assuming for example if in my data file the value is 015.000 or 15.000 or 0015.000 all the cases the HEX encoded value will be 0000000015000C. So as per my requirement how should get the actual raw value from the HEX encoded.

**Comment by yruslan** [comment]
Just a suggestion: `15.000` should should count as the raw value in your example. A number with all trailing zeros removed. Cobrix won't ever unpack  COMP-3 encoded value as '015.000'.

But then again, your requirement depends on the interpretation of what do you mean by 'raw value'. And your notion of 'raw value' depends on your requirements. So all completely up to you.

**Comment by chanduhawk** [comment]
Cobrix won't ever unpack COMP-3 encoded value as '015.000'

then it should be fine. As of now with version 2.0.7 I am planning to use debug option and reverse engineer the hex value to the raw value so that i can use the data as it is with out any changes.

If for future instead of providing HEX if we can provide raw value it will be really good. It seems while adding debug fields in addDebugFields function i guess val debugDataType = AlphaNumeric(s"X($size)", size, None, None, None) will keep the raw value. Please suggest.

**Comment by yruslan** [comment]
Yes, we can add an option to generate raw values for debugging easily, Adding it to the backlog,

> AlphaNumeric(s"X($size)", size, None, None, None) will keep the raw value. Please suggest.

Yes, and also you need to change this method to return raw values instead of HEX:
https://github.com/AbsaOSS/cobrix/blob/a4b24ce72e8f8931cd9f3d1f4310aa2bddc554c1/cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/StringDecoders.scala#L122

**Comment by chanduhawk** [comment]
Thanks a lot. It was great having discussion with you. Do you want me to close this issue or this will be tracked as part of backlog.

**Comment by yruslan** [comment]
No problem 😄

Let's leave this issue open. I'll use it to make the change to support raw values.

**Comment by chanduhawk** [comment]
I have one question for packed decimal field

For field FIELD1 PIC S9(4) COMP.

For the value 530 cobrix converting to 0212 in _debug field. But this value is not actually a HEX value.

The actual HEX for 530 should be F5F3F0

For field FIELD2 PIC S9(3)V99 COMP-3.

For the value 23.20 its converting to 02320C or 02320D. C for positive and D for negative, but this value is also not HEX.

for -23.20 it should be 60F2F34BF2F0

Please let me know for packed decimal COMP and COMP3 the conversion is different.

**Comment by chanduhawk** [comment]
it seems for the packed decimal field `10 Mark PIC S9(10)V999 COMP-3`

** Mark Mark_debug**
15.000 0000000015000C

cobrix does not convert to actual HEX. the value in Mark_debug seems like the data is converted to be stored in ASCII environment. Please confirm

**Comment by yruslan** [comment]
Data in `Mark_debug` should contain HEX of the raw data without any conversion.

Remember, BCD is a binary encoding format. The notion of encoding (EBCDIC vs ASCII) is not applicable here.

**Comment by chanduhawk** [comment]
Got it, Thanks
