### ISSUE TITLE
I want to keep filler columns while reading with Cobrix without dropping those.

### ISSUE THREAD

**Issue by chanduhawk** [AbsaOSS/cobrix#318]
I want to keep filler columns while reading with Cobrix without dropping those. Is it possible using cobrix as currently its dropping filler.

**Comment by yruslan** [comment]
Thanks for this question!

Currently, the only way to retain fillers is to give them names, e.g. `FILLER1`, `FILLER2`, etc.

But this is a very good point and we'll add an option to retain fillers by giving them names automatically.

**Comment by chanduhawk** [comment]
Thanks a lot

**Comment by chanduhawk** [comment]
my assumption is that we will have one more option called **retainFillers** and its default value will be false. In order to make the code backward compatible with the **dropGroupFiller** functionality when **retainFiller** option set to **true**, this will **override** the functionality of **dropGroupFillers**. Because as of now if **dropGroupFiller** set to **false**(which is default) then for the below scenario it will drop its child which is also a FILLER(10   FILLER       PIC X(1).) and the output will be 

FILLER_1
+-------------+
[Joan, Q]

05  FILLER REDEFINES COMPANY_NAME.
               10   STR1         PIC X(5).
               10   STR2         PIC X(2).
               10   FILLER       PIC X(1).

When our new parameter **retainFillers** is set to **true** then it should provide the out put as below

FILLER_1
+-------------+
[Joan, Q, &]

Please confirm on this. Currently I am working on this changes. If you are fine with the above changes then I will raise a PR in couple of days.

**Comment by yruslan** [comment]
The new option `"drop_value_fillers"` which will have a meaning similar to `"drop_group_fillers"` is almost done and will be released soon. I've received an email from you that you are preparing a PR. This won't be necessary, since the feature is almost done.

**Comment by chanduhawk** [comment]
Sure thanks a lot.

**Comment by yruslan** [comment]
'drop_value_fillers' and 'drop_group_fillers' are completely independent options which both can be set to true/false. It is not the best way, but it achieves complete backward compatibility with the way it is implemented before 'drop_value_fillers'.
In your use case you'd need set 'false' for both options. 'drop_group_fillers' is already false by default, so 'drop_value_fillers'. will be sufficient.

In order to make the new feature backwards compatible and to make column name suffix numbers not change when we apply either of options, the suffix for primitive FILLERs is now 'P#', where # is a number, for instance, 'FILLER_P1', 'FILLER_P2'.

You can check this branch: https://github.com/AbsaOSS/cobrix/tree/feature/53-retain-fillers
It will be merged shortly. Let me know if it solves the issue you are having. It will be merged soon. And when we'll release a new version of Cobrix.

**Comment by chanduhawk** [comment]
It will resolve our usecase. Thanks a lot for considering our enhancement requests.

**Comment by yruslan** [comment]
Cool, we plan to release the new version of Cobrix tomorrow.
