### ISSUE TITLE
Cobrix and Databricks DBFS

### ISSUE THREAD

**Issue by kenlmontoya** [AbsaOSS/cobrix#337]
I am very interesting in trying out Cobrix within Databricks/PySpark and just have a few configuration questions to ask if you don't mind.  I have created a cluster and installed the following jar files from the download zip file.  Other than these files, is there any other dependencies?  I will probably not run this locally.

spark-cobol-1.1.2.jar
cobol-parser-1.1.2.jar
scodec-core_2.11-1.10.3.jar
scodec-bits_2.11-1.1.4.jar

I did see an issue where Cobrix does not support S3, so if I was to copy the copybook and data file to the Databricks DBFS mount e.g. /mnt/edl/raw/cobol/copybook and /mnt/edl/raw/cobol/sources, will Cobrix be able to find the files and use them?  Thank you for creating this utility, we spent some time creating a notebook using Python to basically do the same thing but it always requires us to modify it.  Any assistance would be appreciated.

**Comment by yruslan** [comment]
Yes, the dependencies that you listed are the only ones required for v.1.1.2.
But I'd recommend using the latest version v.2.1.3. You would also need `antlr4-runtime-4.7.2`. Thanks for pointing this out. We will update the README.

You can load copybooks from a local file system or a locally mounted filesystem by prepending the path with `file://`. You can specify `.option("copybook", "file:///mnt/edl/raw/cobol/copybook")`.

Source files, however, are expected to be on HDFS or on any other distributed filesystems supported by Spark. Adding support for S3 (and along the way other filesystems supported by Spark) is on our roadmap. We hope to add this support until the end of this year.

Since we are not using DBFS, how would you load, say, CSV file from it? `spark.read. ...`?

**Comment by kenlmontoya** [comment]
Thanks for your response.  Yes, we were hoping we just read the file from the dsfs but since that not supported we might wait until this file system is supported or try going down the path of creating a EC2 HDFS server which is completely outside of current architecture for ingesting on-prem and mainframe data files.

We currently are creating an Avro schema based on the copybook layout using a generator we built and then ssh the mainframe file to S3.  From there the Lamba will trigger and copy the file over to the Databricks mount and we apply a notebook to create the data frame and create a databricks table in raw.  Using your components is much cleaner without all the hops.

**Comment by yruslan** [comment]
Thanks for sharing the use case and the architecture. Yeah, outputting directly to S3 could definitely help here. We will be on in soon.

**Comment by yruslan** [comment]
The support of writing to S3 is supported in Cobrix `2.2.0` and later
