### ISSUE TITLE
Parsing the data file incorrectly

### ISSUE THREAD

**Issue by jianyu0503** [AbsaOSS/cobrix#354]
I am currently working on a project converting EBCDIC binary file to UTF-8 text file. I am using cobrix but the output seems to be incorrect. I am using the following script to load the datafile and copyBook:

```python
dataFrame = spark.read.format("cobol").options(copybook = copyBook).option("is_record_sequence", "true").load(filename)
``` 
The output is showing as below:
![image](https://user-images.githubusercontent.com/25847196/103030659-3ed4ab80-452a-11eb-8fdc-e7d3d1591aff.png)

A screenshot from original data presentation from mainframe:

![image](https://user-images.githubusercontent.com/25847196/103030543-07fe9580-452a-11eb-81ac-77cda39d286f.png)

It looks like when parsing the data, it always skips the "EOB_FAMILY_NUM" field and that field will always be Null. Other fields are mismatched as well. I have tried adding more options like  ```.option("rdw_adjustment", 4)``` but it doesn't solve the issue. Do you know anything I can do to solve that issues? 

I also attached the copy book screenshot below:

 
![image](https://user-images.githubusercontent.com/25847196/103031034-0da8ab00-452b-11eb-81a5-4859f59e8857.png)

**Comment by yruslan** [comment]
Hi, I think your data does not have 4 byte RDW header.
Please, try removing this option:
`.option("is_record_sequence", "true")`
Otherwise, the first 4 bytes will be heated as an RDW header and not part of the actual record. That's why the output looks shifted by 4 bytes,

If Cobrix complains about data file size not divisible by record size, use this option to specify the record size:
`.option("record_length", "100")`
(replace 100 by your record size)

**Comment by jianyu0503** [comment]
Thank you so much for the reply! 

My data file is a variable block file. Even through I removed the option
```python
.option("is_record_sequence", "true")
```
and add the option for “record_length" it's still keep throwing the error "data file size not divisible by record size".
I am also wondering for a variable block file, what record size should i put? Really appreciate your answer.

**Comment by yruslan** [comment]
I have a couple of ideas about the file you are reading. I usually start by checking if a file has an RDW header by exploring the beginning of the file using a HEX editor, like HxD (for Windows) or Hex Fiend (for Mac).
Since the file is a variable block one, maybe RDW headers are big-endian (Cobrix reads them as little-endian by default).
You can try:
```
.option("is_record_sequence", "true")
.option("is_rdw_big_endian", "true")
```

If that doesn't work, it might be that the file contains both BDW and RDW headers. (https://www.ibm.com/support/knowledgecenter/zosbasics/com.ibm.zos.zconcepts/zconcepts_159.htm). If that is the case, it might be that such files are not supported yet. Could I ask you to provide an example file and a copybook and I'll take a look and hopefully quickly add support for such type of files.

**Comment by jianyu0503** [comment]
Hi, thank you for spending time looking into that. I add the following options but it's still not working.
```python
.option("is_record_sequence", "true")
.option("is_rdw_big_endian", "true")
```
I would like to provide an example file and a copybook but it looks like i can't attach a binary file here. Is it somewhere i can upload it to?

**Comment by jianyu0503** [comment]
i didn't see the RDW through the HEX editor. Maybe someone FTP a Variable Blocked dataset, FTP will remove the record descriptor word in front of each record and block. I can figure out if it is possible to keep the RDW when FTP a file. But if RDW is missing, is it a way the Cobrix can handle that? 

![image](https://user-images.githubusercontent.com/25847196/103154844-7a5cb900-4768-11eb-83eb-a0507b8b3ca6.png)

**Comment by yruslan** [comment]
In order to read variable record length files, there should be a way to determine the record length for each record. RDW is the best way, it is general, explicit, and deterministic. So if you can preserve RDW it would be very easy to extract data from the file. 
Other options are more complicated. If one of the record fields contains record size, it can be used. If there is no such field, but there is a field that determines record type, a custom record extractor can be used.

You can send the file and the copybook (or links to them on GDrive/Dropbox) to yruslan@gmail.com.

**Comment by jianyu0503** [comment]
Hi Ruslan, after getting my new files with RDW. Cobrix is working perfectly fine now. Thanks again!
