### ISSUE TITLE
FILLER OCCURS not working

### ISSUE THREAD

**Issue by Loganhex2021** [AbsaOSS/cobrix#463]
## Describe the bug
When copybook has FILLER OCCURS for the specific field , dataframe not returning the results.

## To Reproduce
For the Entity Employee, the below is sample copybook
CopyBook:
01  EMPLOYEE
      05  Name
      05  COMMENTS
            10  FILLER                OCCURS  6.
                  20  COMMENTS  PIC X(60).
      05  JOB-DESCRIPTION
            10  FILLER                OCCURS  3.
                  20  COMMENTS  PIC X(60).

## Expected behaviour
Need to get 6 times of the column from the dataframe like below.

For 1st filler, FILLER_000_[00]_COMMENT, FILLER_000_[01]_COMMENT,etc... till FILLER_000_[06]_COMMENT 
For 2nd filler, FILLER_001_[00]_COMMENT, FILLER_001_[01]_COMMENT,etc... till FILLER_001_[06]_COMMENT

**Comment by Loganhex2021** [comment]
@yruslan - please let me know if you have any comments on this issue

**Comment by yruslan** [comment]
Fillers are dropped by design since fillers represent unnamed space. If you do want to retain them you can either:
- use one of the [drop filler options](https://github.com/AbsaOSS/cobrix#group-filler-dropping) (`.option("drop_group_fillers", "false")`, `.option("drop_value_fillers", "false")`)
- rename the filer as a FILLER1, for example.

**Comment by Loganhex2021** [comment]
ok thanks , let me try

**Comment by yruslan** [comment]
Did it work for you?

**Comment by Loganhex2021** [comment]
Apologies for late response, it was copybook issue and worked after changing copybook
