### ISSUE TITLE
Identifying REDEFINE fields in MultiKeyMap 

### ISSUE THREAD

**Issue by manaac** [AbsaOSS/cobrix#464]
hi. we are using CopybookParser.parseSimple method to get the MultiKeyMap which has the field name (s) and its data type.

Is there any method which actually returns the REDEFINED fields with a flag or something?

For example, 
   01  COMPANY-DETAILS.
            05  SEGMENT-ID        PIC X(5).
            05  COMPANY-ID        PIC X(10).
            05  STATIC-DETAILS.
               10  COMPANY-NAME      PIC X(15).
               10  ADDRESS           PIC X(25).
               10  TAXPAYER.
                  15  TAXPAYER-TYPE  PIC X(1).
                  15  TAXPAYER-STR   PIC X(8).
                  15  TAXPAYER-NUM  REDEFINES TAXPAYER-STR
                                     PIC 9(8)

MultiKeyMap at CopybookParser.parseSimple will have the value as "COMPANY-DETAILS, TAXPAYER-STR X(8)" and "COMPANY-DETAILS, TAXPAYER-NUM 9(8)"

Is there any method will return the MultiKeyMap or any other Map with  "COMPANY-DETAILS, TAXPAYER-STR X(8)" and "COMPANY-DETAILS, TAXPAYER-NUM 9(8) **REDEFINE**"

**Comment by yruslan** [comment]
Hi, sorry, I'm not quite following what you are trying to achieve. Probably it is something that is not implemented since the AST generated by `parseSimple()` does not have a MultiMap (or any other associative collections) in its representation.

But each field in AST has 2 fields:
 - `isRedefined` - is set to true is the specified field is redefined by some other field
 - `redefines` - specified a field which this field redefines. 
A field can be both redefine and redefined by.

**Comment by yruslan** [comment]
Closing for now because of inactivity. Write a comment to repoen.
