### ISSUE TITLE
EBCDIC files received don't have  Record Descriptor Word (RDW) but the file have variable length record

### ISSUE THREAD

**Issue by swami2018** [AbsaOSS/cobrix#51]
I am trying to read a header record file and it have variable length fields. But the file don't have a Record Descriptor Word (RDW). On reading the file, i could see first 4 characters getting truncated as i am using the option 'option("is_record_sequence", "true")'. Is there anyway to avoid this truncation.

**Comment by yruslan** [comment]
Currently the only way to load a variable length record file is by relying on RDW header. Otherwise Cobrix won't know sizes of each record.

Could you elaborate on your use case a little bit more. In particular,
- What is your copybook?
- What acts as a record delimiter in your file?
- Where in the file a record length is defined?
- Could we take a look at a sample of such file?

**Comment by swami2018** [comment]
We can close this issue. The file is fixed length file but have array elements in it. Initial assumption was the array can upto the 0 to maximum array size defined but in MF all the array elements have to be defined.
