### ISSUE TITLE
Can we upgrade ANTLR version to 4.8?

### ISSUE THREAD

**Issue by dz-1** [AbsaOSS/cobrix#561]
## Background [Optional]
When we use cobol-parser:2.6.2 with spark-sql:3.1.3, we get ANTLR warning messages as below.

> ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8
> ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8

## Question
Can we upgrade the version of ANTLR to 4.8 in cobol-parser pom.xml? I checked the ANTLR release notes. It shouldn't impact the existing function.

**Comment by yruslan** [comment]
Yes, updating ANTLR could be good idea, as long as `spark-cobol` is still compatible with Spark 4.8.

But is it enough to just update the runtime dependency? Probably the parser should be re-generated from .g4 to .java files. Otherwise, you might still get the warnings you mentioned.

We are aware of the issue and our approach is to build `spark-cobol` using `sbt assembly` according to this: https://github.com/AbsaOSS/cobrix#creating-an-uber-jar

When you are using 'sbt assembly' to build the jar, ANTLR dependencies are shaed/relocated. So Spark can use whatever version of ANTLR while Cobrix can use its own version. So the warning disappears.

**Comment by dz-1** [comment]
Thanks. We are in a very controlled environment. We don't have the flexibility as the way you suggested.

**Comment by yruslan** [comment]
Thanks again for the PR. However, as I said, it is not sufficient to remove the warnings. Parsers (COBOL and JSON) should be recompiled using 4.8 tool.

I emphasize your intent to be a perfectionist, so here is the PR that (together with yours) should fix the warnings you mentioned:
https://github.com/AbsaOSS/cobrix/pull/563

Note that for our parsers 4.8 produces _exactly_ the same code. So these warnings are absolutely nothing to worry about. But it was fun to fix. 😄

**Comment by dz-1** [comment]
> Thanks again for the PR. However, as I said, it is not sufficient to remove the warnings. Parsers (COBOL and JSON) should be recompiled using 4.8 tool.
> 
> I emphasize your intent to be a perfectionist, so here is the PR that (together with yours) should fix the warnings you mentioned: #563
> 
> Note that for our parsers 4.8 produces _exactly_ the same code. So these warnings are absolutely nothing to worry about. But it was fun to fix. 😄

Thanks, @yruslan. Cobrix is the core of our data ingestion tools. So, we want to make sure it works properly :)

**Comment by yruslan** [comment]
Thanks for your contribution!
