### ISSUE TITLE
NoClassDefFoundError: Could not initialize class za.co.absa.cobrix.cobol.parser.decoders.FloatingPointDecoders$

### ISSUE THREAD

**Issue by devoplib** [AbsaOSS/cobrix#667]
I am using Cobrix to convert EBCDIC to ASCII in Databricks and I am using Databricks [14.3 LTS (includes Apache Spark 3.5.0, Scala 2.12)] and I am able to run the conversion if I use maven library za.co.absa.cobrix:spark-cobol_2.12:2.6.9 copied using Databricks Library install using maven.

If I load the following jar files onto Databricks cluster it is giving the following error.
NoClassDefFoundError: Could not initialize class za.co.absa.cobrix.cobol.parser.decoders.FloatingPointDecoders$

Jars initially loaded that gave error:
cobol-parser_2.12-2.6.9.jar
spark-cobol_2.12-2.6.9.jar

I thought I need to add scode jars and added the following but getting the same error.
scodec_core_2_12_1_11_10.ja
scodec-bits_2.12-1.1.12
antlr4-runtime-4.8

Please advise.

**Comment by yruslan** [comment]
Hi @devoplib , we publish only thin artifacts on Maven. In order to use it in Databricks you need to either include Cobrix as a library Maven dependency, or build your own uber jar, or download the bundle that matches your Scala version here:

https://github.com/AbsaOSS/cobrix/releases/tag/v2.6.11

In your case this is https://github.com/AbsaOSS/cobrix/releases/download/v2.6.11/spark-cobol_2.12-2.6.11-bundle.jar

**Comment by devoplib** [comment]
Thank you very much and appreciate your quick response. I will try the bundle and post an update.

**Comment by devoplib** [comment]
Thank you very much and it worked now.
