### ISSUE TITLE
Top level REDEFINES

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#72]
I have a copybook that has a format akin to the following

```
***********************************************************************
       01 RECORD-TYPE-1.
           02  FIELD-1            PIC X(16).
       01 RECORD-TYPE-2 REDEFINES RECORD-TYPE-1.
           02  FIELD-2            PIC X(16).
       01 RECORD-TYPE-3 REDEFINES RECORD-TYPE-1.
           02  FIELD-3            PIC X(16).
***********************************************************************
```

The library is reading this as a copybook of size 48 (3*16) but should be only 16 in size.  The following copybook, which adds a root element, seems to work correctly (and is a workaround right now):

```
***********************************************************************
      01 RECORD.
       02 RECORD-TYPE-1.
           03  FIELD-1            PIC X(16).
       02 RECORD-TYPE-2 REDEFINES RECORD-TYPE-1.
           03  FIELD-2            PIC X(16).
       02 RECORD-TYPE-3 REDEFINES RECORD-TYPE-1.
           03  FIELD-3            PIC X(16).
***********************************************************************
```

**Comment by yruslan** [comment]
Yeah, this is a side effect of a known issue. Currently the parser is structured in a way that i threats root nodes differently form nested nodes. There is no reason for this. We definitely need to fix it at some point. It might take more time than the other issues, but luckily there is a workaround.

**Comment by tr11** [comment]
I tried to add this feature in [this](https://github.com/tr11/cobrix/tree/issue/72-top-level-redefines) branch, but it seems to trip on the `segmentRedefines`.  Right now it seems that for a `FixedLenReader` there is no way to pass in those redefines.
The result is a successfully parsed schema that reflects the first copybook above, but the reader then proceeds to ignore the Redefined fields due to the isSegmentRedefine property.

**Comment by yruslan** [comment]
I think you've done some really good work here. Thanks a lot! Feel free to create a PR. Will be happy to review and merge. Yes, switching AST from `Seq[Group]` to `Group` is exactly what I had in mind. 

The segment redefines are currently supported only for variable record length files since it was expected that multisegment files have always variable record length. If your use case is different, this is a separate issue, we can implement it as well. I'm going to create a placeholder issue for that.

For now you can try workaround it by adding `.option("generate_record_id", true)`. This will trigger the variable record length reader since records become order-dependent. Please let me know if it works.
